#!/bin/bash

set -e

case "$1" in
    configure)
        if [ -f /usr/share/cloudstack-management/webapps/client/plugins/plugins.js ]; then
            if ! grep -q ccs /usr/share/cloudstack-management/webapps/client/plugins/plugins.js; then
                echo "Enabling CloudStack Container Service UI Plugin"
                rm -f /usr/share/cloudstack-management/webapps/client/plugins/plugins.js.gz
                sed -i  "/cloudStack.plugins/a 'ccs'," /usr/share/cloudstack-management/webapps/client/plugins/plugins.js
                gzip -c /usr/share/cloudstack-management/webapps/client/plugins/plugins.js > /usr/share/cloudstack-management/webapps/client/plugins/plugins.js.gz
            fi
        fi
        ;;
esac

curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.2.4/bin/linux/amd64/kubectl
chmod +x /usr/bin/kubectl

exit 0
