#!/bin/bash

set -e

case "$1" in
    remove|purge)
        if [ -f /usr/share/cloudstack-management/webapps/client/plugins/plugins.js ]; then
            if grep -q ccs /usr/share/cloudstack-management/webapps/client/plugins/plugins.js; then
                echo "Disabling CloudStack Container Service UI Plugin"
                rm -f /usr/share/cloudstack-management/webapps/client/plugins/plugins.js.gz
                sed -i  "/'ccs'/d" /usr/share/cloudstack-management/webapps/client/plugins/plugins.js
                gzip -c /usr/share/cloudstack-management/webapps/client/plugins/plugins.js > /usr/share/cloudstack-management/webapps/client/plugins/plugins.js.gz
            fi
        fi
        ;;
esac

exit 0
