#!/bin/bash

set -e

case "$1" in
    configure)
        if [ -f /usr/share/cloudstack-management/webapp/plugins/plugins.js ]; then
            if ! grep -q ccs /usr/share/cloudstack-management/webapp/plugins/plugins.js; then
                echo "Enabling CloudStack Container Service UI Plugin"
                sed -i  "/cloudStack.plugins/a 'ccs'," /usr/share/cloudstack-management/webapp/plugins/plugins.js
            fi
        fi
        ;;
esac

exit 0
