#cloud-config

---
write-files:
  - path: /opt/bin/setup-kube-system
    permissions: 0700
    owner: root:root
    content: |
      #!/bin/bash -e
      export PATH=$PATH:/opt/bin

      CNI_VERSION="v0.7.1"
      mkdir -p /opt/cni/bin
      curl -L "http://172.20.0.1/files/cni/${CNI_VERSION}/cni-plugins-amd64-${CNI_VERSION}.tgz" | tar -C /opt/cni/bin -xz

      CRICTL_VERSION="v1.11.1"
      mkdir -p /opt/bin
      curl -L "http://172.20.0.1/files/cri-tools/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C /opt/bin -xz

      RELEASE="v1.11.4"
      mkdir -p /opt/bin
      cd /opt/bin
      curl -L --remote-name-all http://172.20.0.1/files/k8s/${RELEASE}/{kubeadm,kubelet,kubectl}
      chmod +x {kubeadm,kubelet,kubectl}

      curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/kubelet.service" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service
      mkdir -p /etc/systemd/system/kubelet.service.d
      curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/10-kubeadm.conf" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      systemctl enable kubelet && systemctl start kubelet
      sysctl net.bridge.bridge-nf-call-iptables=1

      kubeadm config images pull

  - path: /opt/bin/deploy-kube-system
    permissions: 0700
    owner: root:root
    content: |
      #!/bin/bash -e
      modprobe ip_vs
      modprobe ip_vs_wrr
      modprobe ip_vs_sh
      modprobe nf_conntrack_ipv4
      export PATH=$PATH:/opt/bin
      kubeadm join {{ k8s_master.default_ip }}:6443 --token a4qgg6.84hjisyqzvth7yp6 --discovery-token-unsafe-skip-ca-verification

coreos:
  units:
    - name: docker.service
      command: start
      enable: true

    - name: setup-kube-system.service
      command: start
      content: |
        [Unit]
        Requires=docker.service
        After=docker.service

        [Service]
        Type=simple
        StartLimitInterval=0
        ExecStart=/opt/bin/setup-kube-system

    - name: deploy-kube-system.service
      command: start
      content: |
        [Unit]
        After=setup-kube-system.service

        [Service]
        Type=simple
        StartLimitInterval=0
        Restart=on-failure
        ExecStartPre=/usr/bin/curl -k https://{{ k8s_master.default_ip }}:6443/version
        ExecStart=/opt/bin/deploy-kube-system

  update:
    group: stable
    reboot-strategy: off
