#!/usr/bin/python
# -*- coding: utf-8 -*-

import hashlib, hmac, string, base64, urllib
import json, urllib
import argparse
import httplib
from urlparse import urlparse
import getpass
from uuid import UUID

def checkUrl(url):
    try:
        p = urlparse(url)
        conn = httplib.HTTPConnection(p.netloc)
        conn.request('HEAD', p.path)
        resp = conn.getresponse()
        return resp.status < 400
    except:
        return False


class SignedAPICall(object):

    def __init__(self, api_url, apiKey, secret):
        self.api_url = api_url
        self.apiKey = apiKey
        self.secret = secret

    def request(self, args):
        args['apiKey'] = self.apiKey

        self.params = []
        self._sort_request(args)
        self._create_signature()
        self._build_post_request()

    def _sort_request(self, args):
        keys = sorted(args.keys())

        for key in keys:
            self.params.append(key + '=' + urllib.quote_plus(args[key]))

    def _create_signature(self):
        self.query = '&'.join(self.params)
        digest = hmac.new(
            self.secret,
            msg=self.query.lower(),
            digestmod=hashlib.sha1).digest()

        self.signature = base64.b64encode(digest)

    def _build_post_request(self):
        self.query += '&signature=' + urllib.quote_plus(self.signature)
        self.value = self.api_url + '?' + self.query


class CloudStack(SignedAPICall):

    def __getattr__(self, name):
        def handlerFunction(*args, **kwargs):
            if kwargs:
                return self._make_request(name, kwargs)
            return self._make_request(name, args[0])
        return handlerFunction

    def _http_get(self, url):
        response = urllib.urlopen(url)
        return response.read()

    def _make_request(self, command, args):
        args['response'] = 'json'
        args['command'] = command
        self.request(args)
        data = self._http_get(self.value)
        # The response is of the format {commandresponse: actual-data}
        key = command.lower() + "response"
        print data
        return json.loads(data)[key]


usage = """%prog format hypervisor url extractable zoneid

Registers a template of the given format and for the given hypervisor available at specified url with CloudStack. If template at url is extractable set --extractable to true"""

parser = argparse.ArgumentParser()
parser.add_argument("format", help="Template image format" )
parser.add_argument("hypervisor", help="Hypervisor type")
parser.add_argument("url", help=" A valid url at which template is available")
parser.add_argument("extractable", help="if template is extractable")
parser.add_argument("zoneid", help="zoneid in which template is to be installed")

args = parser.parse_args()

image_formats = ['VHD', 'QCOW2', 'VMDK', 'RAW', 'OVA']
hypervisors = ['XenServer', 'KVM', 'VMware']

if args.format not in image_formats:
    print "ERROR: Image has to one of the formats [" + ' '.join(image_formats) + "]"
    exit(1)

if args.hypervisor not in hypervisors:
    print "Hypervisor has to one of the formats [" + ' '.join(hypervisors) + "]"
    exit(1)

if not checkUrl(args.url):
    print "Invalid or not reachable url"
    exit(1)

if args.extractable not in ('true', 'false'):
    print "extractable should be either true of false"
    exit(1)

try:
    UUID(args.zoneid, version=4)
except:
    print "zone id is not a valid uuid"
    exit(1)



name = 'ShapeBlue-CCS-Template'
displaytext = 'ShapeBlue-CCS-Template'

request = {'name': name, 'displaytext': displaytext, 'format': args.format, 'hypervisor': args.hypervisor, 'ostypeid': '99', 'url': args.url, 'zoneid': args.zoneid, 'isextractable': args.extractable, 'ispublic':'true', 'isfeatured':'true'}

api_url = raw_input("API url:")
api_key = getpass.getpass("API Key:")
secret_key = getpass.getpass("Secreat:")

api = CloudStack(api_url, api_key, secret_key)
try:
    result = api.registerTemplate(request)
    print "Template for ShapeBlue CloudStack Container Service is successfully installed"
except Exception as e:
    print "Failed to register template for ShapeBlue CloudStack Container Service due to :" + str(e)
